spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nb_database
    username: root
    password: Sy1568473
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource # 指定数据库的类型

  # 配置jdbc
  jdbc:
    template:
      query-timeout: 3

  # 配置redis
  redis:
#    url: redis://shishi:Sy1568473$@r-bp11qs2ctz7w70xetcpd.redis.rds.aliyuncs.com:6379
    host: r-bp11qs2ctz7w70xetcpd.redis.rds.aliyuncs.com
    port: 6379
    password: shishi:Sy1568473$
    client-type: jedis
    jedis:
      pool:
        max-active: 10
#    client-type: lettuce
#    lettuce:
#      pool:
#        max-active: 10
#        min-idle: 5


# 配置Mybatis
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml # 设置mybatis全局配置文件中的相关配置项
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration: # 设置mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true # 开启驼峰命名策略
