spring:
  mvc:
    # 访问静态资源的路径前缀
#    static-path-pattern: /res/**
    hiddenmethod:
      filter:
        enabled: true # 开启页面表单的Rest功能，选择性开启

    resources:
      # 访问静态资源的默认路径
      static-locations: [classpath:/staticData/]
      # 允许访问静态资源
      add-mappings: true
      cache:
        period: 1100

server:
  servlet:
    context-path: /world